const Marketdata = [
    {
      issuer: "Edelweiss AMC",
      name: "Edelweiss Exchange Traded Scheme - NIFTY",
      symbol: "NIFTYBEES",
      underlying: "NIFTY 50 Index",
      launchDate: "May 2015",
    },
    {
      issuer: "ICICI Prudential AMC",
      name: "ICICI Prudential NIFTY ETF",
      symbol: "ICICINIFTY",
      underlying: "NIFTY 50 Index",
      launchDate: "Mar 2013",
    },
    {
      issuer: "Kotak AMC",
      name: "Kotak NIFTY ETF",
      symbol: "KOTAKNIFTY",
      underlying: "NIFTY 50 Index",
      launchDate: "Feb 2010",
    },
    {
      issuer: "Motilal Oswal AMC",
      name: "MOSt Shares M50",
      symbol: "M50",
      underlying: "NIFTY 50 Index",
      launchDate: "Jul 2010",
    },
    {
      issuer: "Quantum AMC",
      name: "Quantum Index Fund - Growth",
      symbol: "QNFIFTY",
      underlying: "NIFTY 50 Index",
      launchDate: "Jul 2008",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "Reliance NIFTY ETF",
      symbol: "RELIANCE",
      underlying: "NIFTY 50 Index",
      launchDate: "Jan 2011",
    },
    {
      issuer: "SBI AMC",
      name: "SBI ETF NIFTY 50",
      symbol: "SETFNIF50",
      underlying: "NIFTY 50 Index",
      launchDate: "Jul 2015",
    },
    {
      issuer: "UTI AMC",
      name: "UTI NIFTY ETF",
      symbol: "UTINIFTETF",
      underlying: "NIFTY 50 Index",
      launchDate: "Sep 2015",
    },
    {
      issuer: "Birla Sun Life AMC",
      name: "Birla Sun Life NIFTY ETF",
      symbol: "BSLNIFTY",
      underlying: "NIFTY 50 Index",
      launchDate: "Jul 2011",
    },
    {
      issuer: "ICICI Prudential AMC",
      name: "ICICI Prudential CNX 100 ETF",
      symbol: "ICICINF100",
      underlying: "NIFTY 100",
      launchDate: "Aug 2013",
    },
    {
      issuer: "Kotak AMC",
      name: "Kotak Banking ETF",
      symbol: "KOTAKBKETF",
      underlying: "NIFTY Bank",
      launchDate: "Dec 2014",
    },
    {
      issuer: "SBI AMC",
      name: "SBI ETF Banking",
      symbol: "SETFBK",
      underlying: "NIFTY Bank",
      launchDate: "Mar 2015",
    },
    {
      issuer: "Motilal Oswal AMC",
      name: "MOSt Shares M100",
      symbol: "M100",
      underlying: "NIFTY Midcap 100",
      launchDate: "Jan 2011",
    },
    {
      issuer: "SBI AMC",
      name: "SBI ETF NIFTY Junior",
      symbol: "SETFN50",
      underlying: "NIFTY Next 50",
      launchDate: "Mar 2015",
    },
    {
      issuer: "Kotak AMC",
      name: "Kotak PSU Bank ETF",
      symbol: "KOTAKPSUBK",
      underlying: "NIFTY PSU BANK",
      launchDate: "Nov 2007",
    },
    {
      issuer: "ICICI Prudential AMC",
      name: "ICICI SENSEX Prudential Exchange Traded Fund",
      symbol: "ICICISENSX",
      underlying: "S&P BSE Sensex",
      launchDate: "Jan 2003",
    },
    {
      issuer: "UTI AMC",
      name: "UTI Sensex ETF",
      symbol: "UTISENSETF",
      underlying: "S&P BSE Sensex",
      launchDate: "Sep 2015",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "Reliance ETF NIFTY BeES",
      symbol: "NIFTYBEES",
      underlying: "NIFTY 50 Index",
      launchDate: "Dec 2001",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "Reliance ETF NIFTY 100",
      symbol: "NETFNIFTY100",
      underlying: "NIFTY 100",
      launchDate: "Mar 2013",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "Reliance ETF Bank BeES",
      symbol: "BANKBEES",
      underlying: "NIFTY Bank",
      launchDate: "May 2004",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "CPSE ETF",
      symbol: "CPSEETF",
      underlying: "NIFTY CPSE Index",
      launchDate: "Mar 2014",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "Reliance ETF Dividend Opportunities",
      symbol: "NETFDIVOPP",
      underlying: "NIFTY Dividend Opportunities 50",
      launchDate: "Apr 2014",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "Reliance ETF Consumption",
      symbol: "NETFCONSUM",
      underlying: "NIFTY India Consumption",
      launchDate: "Apr 2014",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "Reliance ETF Infra BeES",
      symbol: "INFRABEES",
      underlying: "NIFTY Infrastructure",
      launchDate: "Sep 2010",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "Reliance ETF Junior BeES",
      symbol: "JUNIORBEES",
      underlying: "NIFTY Next 50",
      launchDate: "Feb 2003",
    },
    {
      issuer: "Reliance Nippon Life Asset Management Limited",
      name: "Reliance ETF PSU Bank BeES",
      symbol: "PSUBNKBEES",
      underlying: "NIFTY PSU BANK",
      launchDate: "Oct 2007",
    },
    {
      issuer: "ICICI Prudential AMC",
      name: "BHARAT 22 ETF",
      symbol: "ICICIB22",
      underlying: "S&P BSE BHARAT 22 Index",
      launchDate: "Nov 2017",
    },
  ];
  
  export default Marketdata;