import tcs from '../assest/tcs.png';
import reliance from '../assest/reliance.png';
import hdfc from '../assest/hdfcbank.png';
import bharti from '../assest/bhartiartl.png';
import icici from '../assest/icicibank.png';
import infosys from '../assest/infy.png';
import sbi from '../assest/sbin.png';
import life from '../assest/lici.png';
import itc from '../assest/itc.png';
import hindustan from '../assest/hindunilvr.png';
import larsen from '../assest/Lt.png';
import hcl from '../assest/hcltech.png';
import bajaj from '../assest/bajajhfl.png';
import sun from '../assest/sunteck.png';
import mahindra from '../assest/mahabank.png';
import kotak from '../assest/kotakbank.png';
import axis from '../assest/axisbank.png';
import maruti from '../assest/maruti.png';
import ultratech from '../assest/ultracemco.png';
import ntpc from '../assest/ntpc.png';

export const screenerStockvaluationData = [
  {
    symbol: "RELIANCE INDUSTRIES LTD",
    marketCap: "₹17.23T",
    marketCapPerf: "+10.33%",
    pToE: "25.35",
    pToB: "-",
    peg: "2.32",
    pToS: "1.96",
    pToCF: "2.10",
    sector: "Energy (Oil & Gas)",
    price: "₹2,400",
    ev: "₹150",
    evEbitda: "19.81",
    evSales: "2.28",
    evEbit: "12.09",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: reliance,
  },
  {
    symbol: "TATA CONSULTANCY SERVICES LTD",
    marketCap: "₹12.45T",
    marketCapPerf: "+8.50%",
    pToE: "30.22",
    pToB: "9.50",
    peg: "1.89",
    pToS: "4.55",
    pToCF: "3.10",
    sector: "IT Services",
    price: "₹3,200",
    ev: "₹200",
    evEbitda: "18.12",
    evSales: "5.35",
    evEbit: "13.45",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: tcs,
  },
  {
    symbol: "HDFC BANK LTD",
    marketCap: "₹10.15T",
    marketCapPerf: "+6.75%",
    pToE: "18.90",
    pToB: "3.20",
    peg: "1.25",
    pToS: "2.15",
    pToCF: "2.40",
    sector: "Banking",
    price: "₹1,500",
    ev: "₹140",
    evEbitda: "15.50",
    evSales: "3.18",
    evEbit: "11.20",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: hdfc,
  },
  {
    symbol: "BHARTI AIRTEL LTD",
    marketCap: "₹8.20T",
    marketCapPerf: "+9.50%",
    pToE: "35.00",
    pToB: "4.85",
    peg: "2.10",
    pToS: "3.20",
    pToCF: "2.85",
    sector: "Telecom",
    price: "₹600",
    ev: "₹125",
    evEbitda: "20.10",
    evSales: "4.50",
    evEbit: "12.30",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: bharti,
  },
  {
    symbol: "ICICI BANK LTD",
    marketCap: "₹7.60T",
    marketCapPerf: "+7.25%",
    pToE: "17.45",
    pToB: "2.80",
    peg: "1.15",
    pToS: "2.00",
    pToCF: "2.30",
    sector: "Banking",
    price: "₹900",
    ev: "₹110",
    evEbitda: "14.30",
    evSales: "2.90",
    evEbit: "10.70",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: icici,
  },
  {
    symbol: "INFOSYS LTD",
    marketCap: "₹6.80T",
    marketCapPerf: "+5.75%",
    pToE: "28.10",
    pToB: "8.50",
    peg: "1.75",
    pToS: "4.00",
    pToCF: "3.00",
    sector: "IT Services",
    price: "₹1,800",
    ev: "₹180",
    evEbitda: "17.50",
    evSales: "4.80",
    evEbit: "13.20",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: infosys,
  },
  {
    symbol: "STATE BANK OF INDIA",
    marketCap: "₹5.50T",
    marketCapPerf: "+6.00%",
    pToE: "15.30",
    pToB: "1.50",
    peg: "1.00",
    pToS: "1.80",
    pToCF: "2.10",
    sector: "Banking",
    price: "₹500",
    ev: "₹100",
    evEbitda: "12.80",
    evSales: "2.50",
    evEbit: "9.75",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: sbi,
  },
  {
    symbol: "LIFE INSURANCE CORP OF INDIA",
    marketCap: "₹5.20T",
    marketCapPerf: "+4.50%",
    pToE: "12.00",
    pToB: "1.20",
    peg: "-",
    pToS: "1.50",
    pToCF: "1.90",
    sector: "Insurance",
    price: "₹800",
    ev: "₹90",
    evEbitda: "10.50",
    evSales: "2.00",
    evEbit: "8.00",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: life,
  },
  {
    symbol: "ITC LTD",
    marketCap: "₹4.80T",
    marketCapPerf: "+7.00%",
    pToE: "20.00",
    pToB: "3.00",
    peg: "1.50",
    pToS: "2.20",
    pToCF: "2.60",
    sector: "FMCG",
    price: "₹300",
    ev: "₹95",
    evEbitda: "13.80",
    evSales: "2.80",
    evEbit: "10.00",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: itc,
  },
  {
    symbol: "HINDUSTAN UNILEVER LTD",
    marketCap: "₹4.50T",
    marketCapPerf: "-4.15%",
    pToE: "35.50",
    pToB: "10.00",
    peg: "2.25",
    pToS: "4.75",
    pToCF: "3.50",
    sector: "FMCG",
    price: "₹2,600",
    ev: "₹130",
    evEbitda: "22.00",
    evSales: "5.00",
    evEbit: "15.00",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: hindustan,
  },
  {
    symbol: "LARSEN & TOUBRO LTD",
    marketCap: "₹3.90T",
    marketCapPerf: "+6.50%",
    pToE: "22.00",
    pToB: "3.50",
    peg: "1.20",
    pToS: "2.80",
    pToCF: "2.40",
    sector: "Engineering",
    price: "₹1,400",
    ev: "₹110",
    evEbitda: "16.00",
    evSales: "3.10",
    evEbit: "11.80",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: larsen,
  },
  {
    symbol: "HCL TECHNOLOGIES LTD",
    marketCap: "₹3.60T",
    marketCapPerf: "+5.00%",
    pToE: "24.30",
    pToB: "6.00",
    peg: "1.75",
    pToS: "3.50",
    pToCF: "2.80",
    sector: "IT Services",
    price: "₹1,200",
    ev: "₹120",
    evEbitda: "15.50",
    evSales: "3.50",
    evEbit: "10.80",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: hcl,
  },
  // Continue for other companies...

  
  {
    symbol: "BAJAJ HOLDINGS & INVESTMENT LTD",
    marketCap: "₹0.90T",
    marketCapPerf: "+4.10%",
    pToE: "18.00",
    pToB: "2.50",
    peg: "1.20",
    pToS: "2.20",
    pToCF: "2.00",
    sector: "Finance",
    price: "₹6,000",
    ev: "₹80",
    evEbitda: "14.20",
    evSales: "2.60",
    evEbit: "11.30",
    index: "Nifty 50",
    marketCapCategory: "Mid Cap",
    icon: bajaj,
  },
  // Entry for Sunteck Realty
  {
    symbol: "SUNTECK REALTY LTD",
    marketCap: "₹0.20T",
    marketCapPerf: "+3.85%",
    pToE: "16.00",
    pToB: "1.80",
    peg: "1.10",
    pToS: "2.00",
    pToCF: "1.75",
    sector: "Real Estate",
    price: "₹400",
    ev: "₹60",
    evEbitda: "10.00",
    evSales: "1.50",
    evEbit: "8.00",
    index: "Small Cap",
    marketCapCategory: "Small Cap",
    icon: sun,
  },
  // Entry for Bank of Maharashtra
  {
    symbol: "BANK OF MAHARASHTRA",
    marketCap: "₹0.30T",
    marketCapPerf: "+7.20%",
    pToE: "12.50",
    pToB: "0.80",
    peg: "0.90",
    pToS: "1.20",
    pToCF: "1.10",
    sector: "Banking",
    price: "₹40",
    ev: "₹50",
    evEbitda: "8.50",
    evSales: "1.10",
    evEbit: "6.00",
    index: "Small Cap",
    marketCapCategory: "Small Cap",
    icon: mahindra,
  },
  // Entry for Kotak Mahindra Bank
  {
    symbol: "KOTAK MAHINDRA BANK LTD",
    marketCap: "₹4.50T",
    marketCapPerf: "+5.50%",
    pToE: "25.20",
    pToB: "3.60",
    peg: "1.40",
    pToS: "2.50",
    pToCF: "2.20",
    sector: "Banking",
    price: "₹1,800",
    ev: "₹115",
    evEbitda: "13.50",
    evSales: "2.80",
    evEbit: "10.80",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: kotak,
  },
  // Entry for Axis Bank
  {
    symbol: "AXIS BANK LTD",
    marketCap: "₹2.80T",
    marketCapPerf: "+6.25%",
    pToE: "18.10",
    pToB: "2.10",
    peg: "1.00",
    pToS: "2.20",
    pToCF: "1.90",
    sector: "Banking",
    price: "₹950",
    ev: "₹110",
    evEbitda: "12.50",
    evSales: "2.40",
    evEbit: "9.50",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: axis,
  },
  // Entry for Maruti Suzuki
  {
    symbol: "MARUTI SUZUKI INDIA LTD",
    marketCap: "₹3.10T",
    marketCapPerf: "+4.75%",
    pToE: "35.20",
    pToB: "4.50",
    peg: "2.00",
    pToS: "2.75",
    pToCF: "2.20",
    sector: "Automotive",
    price: "₹9,800",
    ev: "₹130",
    evEbitda: "18.10",
    evSales: "3.50",
    evEbit: "13.00",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: maruti,
  },
  // Entry for UltraTech Cement
  {
    symbol: "ULTRATECH CEMENT LTD",
    marketCap: "₹2.85T",
    marketCapPerf: "+8.10%",
    pToE: "35.00",
    pToB: "3.75",
    peg: "1.75",
    pToS: "3.60",
    pToCF: "2.80",
    sector: "Cement",
    price: "₹8,000",
    ev: "₹125",
    evEbitda: "15.40",
    evSales: "3.30",
    evEbit: "11.90",
    index: "Nifty 50",
    marketCapCategory: "Large Cap",
    icon: ultratech,
  },
  // Entry for NTPC
  {
    symbol: "NTPC LTD",
    marketCap: "₹1.80T",
    marketCapPerf: "+5.50%",
    pToE: "12.50",
    pToB: "1.90",
    peg: "1.10",
    pToS: "1.50",
    pToCF: "1.40",
    sector: "Utilities",
    price: "₹150",
    ev: "₹70",
    evEbitda: "9.20",
    evSales: "1.60",
    evEbit: "7.80",
    index: "Nifty 50",
    marketCapCategory: "Mid Cap",
    icon: ntpc,
  },
];