import tcs from '../assest/tcs.png';
import reliance from '../assest/reliance.png';
import hdfc from '../assest/hdfcbank.png';
import bharti from '../assest/bhartiartl.png';
import icici from '../assest/icicibank.png';
import infosys from '../assest/infy.png';
import sbi from '../assest/sbin.png';
import life from '../assest/lici.png';
import itc from '../assest/itc.png';
import hindustan from '../assest/hindunilvr.png';
import larsen from '../assest/Lt.png';
import hcl from '../assest/hcltech.png';
import bajaj from '../assest/bajajhfl.png';
import sun from '../assest/sunteck.png';
import mahindra from '../assest/mahabank.png';
import kotak from '../assest/kotakbank.png';
import axis from '../assest/axisbank.png';
import maruti from '../assest/maruti.png';
import ultratech from '../assest/ultracemco.png';
import ntpc from '../assest/ntpc.png';

export const screenerStockincomeData = [
  {
    symbol: "RELIANCE INDUSTRIES LTD",
    icon: reliance,
    revenue: "₹9.25T",
    revenueGrowth: "+6.37",
    grossProfit: "₹2.38T",
    operatingIncome: "₹1.08T",
    netIncome: "₹679.17B",
    ebitda: "₹1.61T",
    epsDil: "₹50.19",
    epsDilGrowth: "-0.85",
  },
  {
    symbol: "TATA CONSULTANCY SERVICES LTD.",
    icon: tcs,
    revenue: "₹2.49T",
    revenueGrowth: "+5.17",
    grossProfit: "₹780.25B",
    operatingIncome: "₹619.8B",
    netIncome: "₹474.41B",
    ebitda: "₹669.45B",
    epsDil: "₹130.85",
    epsDilGrowth: "+7.22",
  },
  {
    symbol: "HDFC BANK LTD",
    icon: hdfc,
    revenue: "₹1.6T",
    revenueGrowth: "+10.12",
    grossProfit: "₹1.2T",
    operatingIncome: "₹760.45B",
    netIncome: "₹500.3B",
    ebitda: "₹950B",
    epsDil: "₹70.58",
    epsDilGrowth: "+12.5",
  },
  {
    symbol: "BHARTI AIRTEL LTD",
    icon: bharti,
    revenue: "₹1.45T",
    revenueGrowth: "+8.6",
    grossProfit: "₹680.3B",
    operatingIncome: "₹300.4B",
    netIncome: "₹150.2B",
    ebitda: "₹520.3B",
    epsDil: "₹40.65",
    epsDilGrowth: "+5.3",
  },
  {
    symbol: "ICICI BANK LTD",
    icon: icici,
    revenue: "₹1.88T",
    revenueGrowth: "+9.25",
    grossProfit: "₹1.1T",
    operatingIncome: "₹890.2B",
    netIncome: "₹620.45B",
    ebitda: "₹750B",
    epsDil: "₹75.12",
    epsDilGrowth: "+9.75",
  },
  {
    symbol: "INFOSYS LTD",
    icon: infosys,
    revenue: "₹1.4T",
    revenueGrowth: "+6.98",
    grossProfit: "₹720.4B",
    operatingIncome: "₹500.2B",
    netIncome: "₹430.7B",
    ebitda: "₹590.1B",
    epsDil: "₹60.75",
    epsDilGrowth: "+8.25",
  },
  {
    symbol: "STATE BANK OF INDIA",
    icon: sbi,
    revenue: "₹3.2T",
    revenueGrowth: "+11.02",
    grossProfit: "₹2.1T",
    operatingIncome: "₹1.5T",
    netIncome: "₹960.3B",
    ebitda: "₹1.75T",
    epsDil: "₹85.32",
    epsDilGrowth: "+10.15",
  },
  {
    symbol: "LIFE INSURANCE CORPORATION OF INDIA",
    icon: life,
    revenue: "₹2.7T",
    revenueGrowth: "+7.12",
    grossProfit: "₹1.5T",
    operatingIncome: "₹1.02T",
    netIncome: "₹580.4B",
    ebitda: "₹1.15T",
    epsDil: "₹90.2",
    epsDilGrowth: "+5.45",
  },
  {
    symbol: "ITC LTD",
    icon: itc,
    revenue: "₹680.4B",
    revenueGrowth: "+9.4",
    grossProfit: "₹350.5B",
    operatingIncome: "₹280.3B",
    netIncome: "₹200.2B",
    ebitda: "₹310.6B",
    epsDil: "₹35.85",
    epsDilGrowth: "+6.12",
  },
  {
    symbol: "HINDUSTAN UNILEVER LTD",
    icon: hindustan,
    revenue: "₹560.3B",
    revenueGrowth: "+7.75",
    grossProfit: "₹340.2B",
    operatingIncome: "₹250.3B",
    netIncome: "₹180.6B",
    ebitda: "₹290.8B",
    epsDil: "₹30.6",
    epsDilGrowth: "-0.16",
  },
  {
    symbol: "LARSEN & TOUBRO LTD",
    icon: larsen,
    revenue: "₹1.6T",
    revenueGrowth: "+8.5",
    grossProfit: "₹950.6B",
    operatingIncome: "₹600.8B",
    netIncome: "₹420.4B",
    ebitda: "₹750.7B",
    epsDil: "₹70.45",
    epsDilGrowth: "+9.65",
  },
  {
    symbol: "HCL TECHNOLOGIES LTD",
    icon: hcl,
    revenue: "₹950B",
    revenueGrowth: "+6.4",
    grossProfit: "₹480B",
    operatingIncome: "₹360.2B",
    netIncome: "₹300.4B",
    ebitda: "₹450.6B",
    epsDil: "₹55.3",
    epsDilGrowth: "+8.7",
  },
  {
    symbol: "BAJAJ FINANCE LTD",
    icon: bajaj,
    revenue: "₹390.5B",
    revenueGrowth: "+12.5",
    grossProfit: "₹180.7B",
    operatingIncome: "₹140.3B",
    netIncome: "₹110.2B",
    ebitda: "₹150.8B",
    epsDil: "₹180.4",
    epsDilGrowth: "+9.2",
  },
  {
    symbol: "SUNTECK REALTY LTD",
    icon: sun,
    revenue: "₹50.2B",
    revenueGrowth: "+6.8",
    grossProfit: "₹25.1B",
    operatingIncome: "₹15.4B",
    netIncome: "₹10.5B",
    ebitda: "₹18.7B",
    epsDil: "₹12.3",
    epsDilGrowth: "+5.4",
  },
  {
    symbol: "MAHINDRA & MAHINDRA LTD",
    icon: mahindra,
    revenue: "₹1.2T",
    revenueGrowth: "+10.4",
    grossProfit: "₹540.8B",
    operatingIncome: "₹360.2B",
    netIncome: "₹270.6B",
    ebitda: "₹430.3B",
    epsDil: "₹75.5",
    epsDilGrowth: "+7.8",
  },
  {
    symbol: "KOTAK MAHINDRA BANK LTD",
    icon: kotak,
    revenue: "₹900.7B",
    revenueGrowth: "+8.7",
    grossProfit: "₹500.5B",
    operatingIncome: "₹380.6B",
    netIncome: "₹280.4B",
    ebitda: "₹450.8B",
    epsDil: "₹60.2",
    epsDilGrowth: "+9.5",
  },
  {
    symbol: "AXIS BANK LTD",
    icon: axis,
    revenue: "₹1.7T",
    revenueGrowth: "+9.2",
    grossProfit: "₹890B",
    operatingIncome: "₹720.5B",
    netIncome: "₹520.6B",
    ebitda: "₹1T",
    epsDil: "₹60.5",
    epsDilGrowth: "+10.5",
  },
  {
    symbol: "MARUTI SUZUKI INDIA LTD",
    icon: maruti,
    revenue: "₹1.3T",
    revenueGrowth: "+10.3",
    grossProfit: "₹720B",
    operatingIncome: "₹540.1B",
    netIncome: "₹390.2B",
    ebitda: "₹660.5B",
    epsDil: "₹130.4",
    epsDilGrowth: "+7.75",
  },
  {
    symbol: "ULTRATECH CEMENT LTD",
    icon: ultratech,
    revenue: "₹710.4B",
    revenueGrowth: "+8.6",
    grossProfit: "₹350.2B",
    operatingIncome: "₹280.6B",
    netIncome: "₹190.5B",
    ebitda: "₹300.7B",
    epsDil: "₹90.1",
    epsDilGrowth: "+6.8",
  },
  {
    symbol: "NTPC LTD",
    icon: ntpc,
    revenue: "₹1.6T",
    revenueGrowth: "+6.8",
    grossProfit: "₹900B",
    operatingIncome: "₹580.5B",
    netIncome: "₹410.2B",
    ebitda: "₹700.6B",
    epsDil: "₹45.4",
    epsDilGrowth: "+5.6",
  },
];
